[build]
target = "xtensa-esp32s3-none-elf"

[target.xtensa-esp32s3-none-elf]
runner = "espflash flash --monitor"

[unstable]
build-std = ["core"]

[alias]
flash-monitor = "espflash flash --release --chip esp32s3 --port /dev/tty.usbmodem2101 --monitor"
